version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myjenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
